
[build]
command = "npm run build"
publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/auth/*"
  to = "http://103.233.79.221/auth/:splat"
  status = 200
  force = true
